# Generated by Django 3.2.9 on 2021-11-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='re_password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
